export const RequestStatus = {
  requestPhase: {
    IDLE: "IDLE",
    LOADING: "LOADING",
  },
  responsePhase: {
    SUCCESS: "SUCCESS",
    EMPTY: "EMPTY",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    SERVER_ERROR: "SERVER_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATA_CORRUPTION: "DATA_CORRUPTION",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    OUT_OF_STOCK: "OUT_OF_STOCK",
    INPUT_VALIDATION_ERROR: "INPUT_VALIDATION_ERROR",
  },
  errorPhase: {
    ERROR: "ERROR",
    NETWORK_ERROR: "NETWORK_ERROR",
    ABORTED: "ABORTED",
  },
};
